src/component/ActivityCard.tsx
src/component/IconNavLink.tsx
src/component/Navbar.tsx
src/component/PageFrame.less
src/model/Activity.ts
src/model/User.ts
src/page/Activity/EditActivity.tsx
src/page/Activity/ManageParticipant.tsx
src/page/Activity/menu.json
src/page/index.tsx

加左侧导航栏 & 报名用户页

---

src/index.html
src/model/Session.ts
src/model/service.ts
src/page/index.tsx

login with new authing dialog, post the result to new backend api
close #1

fix: login with new authing dialog and backend api

---

.github/workflows/main.yml
.gitignore
.husky/pre-commit
.husky/pre-push
ReadMe.md
package.json
src/component/ActivityCard.tsx
src/component/TimeRange.tsx
src/index.tsx
src/model/AMap.ts
src/model/Activity.ts
src/model/BaseModel.ts
src/model/Registration.ts
src/model/Team.ts
src/model/User.ts
src/model/index.ts
src/model/service.ts
src/page/Activity/ActivityBasicForm.tsx
src/page/Activity/CreateActivity.tsx
src/page/Activity/Detail.tsx
src/page/Activity/EditActivity.tsx
src/page/Activity/List.tsx
src/page/Activity/ManageParticipant.tsx
src/page/Home.tsx
src/page/Team.tsx
src/page/User/Detail.tsx
src/page/User/Edit.tsx
src/page/index.tsx
workbox-config.js

[refactor] upgrade Client-side existed API to v2

---

src/component/AdminFrame.tsx
src/index.tsx
src/model/Activity.ts
src/model/Award.ts
src/model/BaseModel.ts
src/model/Registration.ts
src/model/Team.ts
src/model/index.ts
src/model/service.ts
src/page/Activity/Manage/Award.tsx
src/page/Activity/Manage/BasicForm.tsx
src/page/Activity/Manage/Creator.tsx
src/page/Activity/Manage/Editor.tsx
src/page/Activity/Manage/Participant.tsx
src/page/Activity/Manage/menu.json
src/page/Home.tsx
src/page/User/Detail.tsx
src/page/index.tsx

[add] Award model & management page

---

src/i18n/en-US.ts
src/i18n/zh-CN.ts
src/i18n/zh-TW.ts
src/model/Team.ts
src/page/Activity/Detail.tsx
src/page/Team/Detail.tsx
src/page/Team/Members.tsx
src/page/Team/index.ts
src/page/index.tsx

团队管理员查看团队成员列表，并：
- 修改成员角色
- 审核通过加入团队的申请
- 删除团队成员
close #39

feature: manage team members

---

src/i18n/en-US.ts
src/i18n/zh-CN.ts
src/i18n/zh-TW.ts
src/model/Activity.ts
src/model/Session.ts
src/model/Team.ts
src/model/index.ts
src/model/service.ts
src/page/Activity/Detail.tsx
src/page/Admin/index.tsx
src/page/Team/Detail.tsx
src/page/Team/Edit.tsx
src/page/User/Detail.tsx

1. add Team disbanding
2. optimize Team logos
3. split data of Owned & Other activities
4. optimize Token timed out

[add] Team disbanding

---

.eslintrc.json
src/page/index.tsx

在显示报名页面时检查登录状态，如果没有登录，则先登录
#53

singIn before register for a hackathon

---

package.json

在authing登录框中点登录按钮没反应，是@authing/native-js-ui-components问题，更新到最新版本解决。

fix: update authing ui to fix the login issue

---

.env
components/ActivityCard.tsx
package.json
pages/_app.tsx
pages/api/Activity.ts
pages/api/core.ts
pages/api/home.ts
pages/index.tsx
styles/globals.less
yarn.lock

1. [add] Activity gallery of Home page
2. [add] Activity Card component & list
3. [add] Partner data, logos & links in Home page
4. [add] Core types & Request method of HTTP API

[add] 2022 Home page

---

.env
components/UserBar.tsx
package.json
pages/_app.tsx
pages/api/core.ts
pages/api/user/session.ts
pages/index.tsx
pages/user/sign-in.tsx
yarn.lock

1. [add] User Bar component
2. [add] types & API of Core & Session
3. [refactor] replace Authing React component with Authing Web

[add] 2022 Sign In page based on Authing

---

components/ActivityCard.tsx
components/ActivityControl.tsx
components/ActivityEntry.tsx
components/UserBar.tsx
components/layout/Layout.tsx
models/Activity.ts
pages/activity/[hackathonName].tsx
pages/admin/index.tsx
pages/api/core.ts
pages/api/user/session.ts
pages/index.tsx
tsconfig.json

1. [add] Super Admin page
2. [add] Activity Entry & Control component
3. [add] Client session & request
4. [add] HTTP Error class & safeAPI method

2022 超级管理员页

---

models/Question.ts
pages/activity/[name]/register.tsx
yarn.lock

2022 活动报名页

---

components/ActivityAdministratorModal.tsx
components/ActivityManageFrame.tsx
models/Award.ts
pages/activity/[name]/manage/administrator.tsx
pages/activity/[name]/manage/award.tsx

[add] award model , award page
[polish] administrator handleSubmit function

2022 活动管理 奖项设置

---

components/ActivityCreate.tsx
components/ActivityEdit.tsx
components/ActivityEditor.tsx
components/DateTimeInput.tsx
pages/activity/[name]/edit.tsx

2022 活动编辑页

---

components/ActivityEditor.tsx
components/ActivityEntry.tsx
components/TeamCard.tsx
components/TeamCreateModal.tsx
components/TeamEditor.tsx
models/Enrollment.ts
models/Team.ts
pages/activity/[name]/index.tsx
pages/activity/[name]/manage/award.tsx

Checklist（清单）:
- 增加活动人数输入框限制
- 创建团队

add create Team

---

components/Activity/ActivityManageFrame.tsx
components/CommentBox.tsx
components/Team/TeamList.tsx
models/Staff.ts
package.json
pages/activity/[name]/index.tsx
pages/activity/[name]/manage/team.tsx
pages/activity/[name]/team/[tid].tsx
pnpm-lock.yaml

1. [add] Comment Box component (closes #70)
2. [optimize] Team Manage page supports searching (closes #103)
3. [optimize] Activity Manage pages support Authorization controlling (closes #106)

[add] Comment Box component

---

pages/index.tsx

topUserList background gap margin-top: -3rem invalid  Remove my-5
Checklist（清单）:
Closes #115

[fix] topUserList background gap

---

components/Organization/OrganizationCard.tsx
components/Organization/OrganizationList.tsx
pages/activity/[name]/index.tsx

[feat] activity Organization info

---

components/Activity/ActivityLogList.tsx
components/Message/ActivityMessageModal.tsx
components/Message/MessageEditor.tsx
components/Message/MessageList.tsx
components/Organization/OrganizationList.tsx
models/Activity.ts
models/Log.ts
pages/activity/[name]/index.tsx

[add] activity dynmaic list

---

components/Activity/ActivityManageFrame.tsx
components/GitLogo.tsx
locales/en-US.json
locales/zh-Hans.json
locales/zh-Hant-TW.json
models/Staff.ts
pages/_document.tsx
pages/activity/[name]/manage/log.tsx

[add] manage log page

---

components/Activity/ActivityList.tsx
components/ActivityAdministratorModal.tsx
components/PlatformAdmin/PlatformAdminList.tsx
components/PlatformAdmin/PlatformAdminModal.tsx
components/User/HackathonAdminList.tsx
components/User/LanguageMenu.tsx
components/User/StaffList.tsx
components/User/UserBar.tsx
components/User/UserList.tsx
locales/en-US.json
locales/zh-Hans.json
locales/zh-Hant-TW.json
models/HackathonAdmin.ts
models/PlatformAdmin.ts
models/Staff.ts
pages/admin/platform-admin.tsx

Checklist（清单）:
- Add platform admin
- Refactor some modules(Table)
- Fix the checked error
Closes #132

feat: add platform admin

---

components/work/WorkEdit.tsx

- [polish] WorkEdit title input validate
Checklist（清单）:
Closes #XXXXX

[polish] WorkEdit title input validate

---

LICENSE
README.md
components/Team/TeamAwardAssignment.tsx
components/Team/TeamWorkList.tsx
models/Award.ts
pages/activity/[name]/manage/evaluation.tsx

- [polish] team award list name
- [polish] evaluation assignment sticky position
Checklist（清单）:
- Closes #59

[polish] team award list name

---

components/Activity/ActivityCard.tsx
translation/en-US.ts
translation/zh-CN.ts
translation/zh-TW.ts

[optimize]show register limits on activity cards

---

pages/_app.tsx
translation/en-US.ts
translation/zh-CN.ts
translation/zh-TW.ts

[polish] fix footer en-US translation

---

Dockerfile

fix pnpm compatibility with Node.js

---

components/ActivityEditor.tsx
components/DateTimeInput.tsx
translation/en-US.ts
translation/zh-CN.ts
translation/zh-TW.ts

[feature] add date time comparison logic

---

pages/_app.tsx

[fix] make only text clickable

---

components/Activity/ActivityEditor.tsx

fix：activity_detail check fail

---

.husky/pre-push
components/Activity/ActivityEditor.tsx

Fixed activity detail not triggering reminders in 2 cases

---

components/Activity/ActivityCard.tsx
pages/activity/[name]/activityDetail.module.less
pages/activity/[name]/index.tsx

Optimize：Limit Carousel image height； update ActivityCard layout,show all time,address,title info

---

pages/activity/[name]/activityDetail.module.less
pages/activity/[name]/index.tsx

Fixed : Activity Carousel Image layout error 

---

components/Team/TeamWorkList.tsx
package.json
pnpm-lock.yaml

Checklist（清单）:
Closes [#172](https://github.com/kaiyuanshe/OpenHackathon-Web/issues/172)

feat: use FilePreview display the team's work

---

components/User/ServerSessionBox.tsx
pages/connect/[provider]/redirect.tsx

[migrate] replace GitHub OAuth with Auth0

---

Dockerfile
docker-compose.yml

[![PR-221](https://badgen.net/badge/GitHub.dev/PR-221/blue?icon=visualstudio)](https://github.dev/kaiyuanshe/OpenHackathon-Web/pull/221) [![PR-221](https://badgen.net/badge/GitHub%20codespaces/PR-221/black?icon=github)](https://codespaces.new/kaiyuanshe/OpenHackathon-Web/pull/221) [![PR-221](https://badgen.net/badge/GitPod.io/PR-221/orange?icon=git)](https://gitpod.io/?autostart=true#https://github.com/kaiyuanshe/OpenHackathon-Web/pull/221) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=kaiyuanshe&utm_campaign=badge_info)
Checklist（清单）:
Closes #XXXXX

Feat docker compose deploy

---

Dockerfile

[![PR-224](https://badgen.net/badge/GitHub.dev/PR-224/blue?icon=visualstudio)](https://github.dev/kaiyuanshe/OpenHackathon-Web/pull/224) [![PR-224](https://badgen.net/badge/GitHub%20codespaces/PR-224/black?icon=github)](https://codespaces.new/kaiyuanshe/OpenHackathon-Web/pull/224) [![PR-224](https://badgen.net/badge/GitPod.io/PR-224/orange?icon=git)](https://gitpod.io/?autostart=true#https://github.com/kaiyuanshe/OpenHackathon-Web/pull/224) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=kaiyuanshe&utm_campaign=badge_info)
Checklist（清单）:
Closes #XXXXX

update to node22

---

.github/workflows/docker.yml

[![PR-226](https://badgen.net/badge/GitHub.dev/PR-226/blue?icon=visualstudio)](https://github.dev/kaiyuanshe/OpenHackathon-Web/pull/226) [![PR-226](https://badgen.net/badge/GitHub%20codespaces/PR-226/black?icon=github)](https://codespaces.new/kaiyuanshe/OpenHackathon-Web/pull/226) [![PR-226](https://badgen.net/badge/GitPod.io/PR-226/orange?icon=git)](https://gitpod.io/?autostart=true#https://github.com/kaiyuanshe/OpenHackathon-Web/pull/226) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=kaiyuanshe&utm_campaign=badge_info)
Checklist（清单）:
Closes #XXXXX

feat: use gha cache
